name: shopping_list_v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  equatable: ^2.0.5
  floor: ^1.4.2
  dartz: ^0.10.1
  skeletons: ^0.0.3
  go_router: ^14.2.3
  loading_animation_widget: ^1.2.0+4
  flutter_typeahead: ^5.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan Boom.ttf